- name: Python Markdown Documentation
  # You may pin to the exact commit or the version.
  # uses: jbheard/markdown-docs@c97b542c3d24257d97d55179445e339251618220
  uses: jbheard/markdown-docs@v0.1
  with:
    # Path to the source folder containing python code
    src_path: # optional, default is .
    # Directory to create markdown documents in
    dst_path: # optional, default is docs
